In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import datasets

In [2]:
datasets=datasets.load_iris()

In [3]:
X=datasets['data']
y=datasets['target']

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [5]:
pca=PCA(n_components=3)

In [6]:
#PCA is a transformation technique
X_train=pca.fit_transform(X_train)
X_train

array([[-3.19809613e-01, -6.05348170e-01, -3.26338094e-01],
       [ 1.32748645e+00, -1.10665523e-01, -1.69354196e-01],
       [ 1.79450873e+00,  6.14314403e-02,  1.48612379e-01],
       [ 7.92127577e-01,  3.77984923e-01, -3.07968171e-01],
       [ 2.82233703e+00,  7.62500823e-01,  4.33892944e-01],
       [ 2.57313290e-01, -2.43498191e-01,  6.44412424e-02],
       [ 3.29429267e+00,  5.44686773e-01, -3.52148810e-01],
       [ 5.41525286e-01, -3.17525946e-01,  3.09546404e-01],
       [-2.78933480e+00,  4.41451862e-01, -1.32970257e-03],
       [ 3.39404833e+00,  4.59441452e-01, -5.80769348e-01],
       [ 1.14921657e-01, -2.69437408e-01, -2.86655671e-01],
       [-2.74586793e+00,  4.36734540e-01, -1.18396593e-01],
       [-2.87649191e+00,  3.84090975e-01,  1.04412332e-01],
       [-2.30949060e+00,  5.37738148e-01,  3.22150116e-01],
       [-6.51513641e-01, -1.18461155e+00, -3.05080700e-01],
       [ 1.26934877e+00, -1.73732914e-01, -7.48883663e-02],
       [-2.46688042e+00,  7.31965446e-02

In [7]:
pca.components_

array([[ 0.37167593, -0.06299273,  0.85531578,  0.35542065],
       [ 0.66585782,  0.71303104, -0.19438974, -0.10214078],
       [-0.55627639,  0.61439252,  0.05561896,  0.55676291]])

In [10]:
pca.explained_variance_ratio_

array([0.9191876 , 0.05549301, 0.02010131])